version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "py-surepetcare"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5