version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      day-of-month: 1
    groups:
      dev-tools:
        patterns:
          - black
          - isort
          - flake8
          - mypy
          - pytest*
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day-of-month: 1