repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: uv run pyupgrade --py37-plus
        language: system
        types: [python]
      - id: codespell
        name: codespell
        entry: uv run codespell
        language: system
        args:
          - --ignore-words-list=hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        args:
          - --pretty
          - --show-error-codes
          - --show-error-context
          - --explicit-package-bases
          - --ignore-missing-imports
        files: ^custom_components/surepcha/.*\.py$
