name: Dependabot Sync HACS Home Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  sync-hacs-homeassistant:
    if: |
      github.repository_owner == 'FredrikM97' &&
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.head.ref, 'homeassistant')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependabot branch
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Sync hacs.json homeassistant
        shell: bash
        run: |

          dep_ver=$(python -c 'import tomllib; print(next(dep.split("==", 1)[1] for dep in tomllib.load(open("pyproject.toml", "rb"))["dependency-groups"]["dev"] if dep.startswith("homeassistant==")))')
          [[ -n "$dep_ver" ]] || { echo "Dependency version not found"; exit 0; }
          ha_ver="$dep_ver"

          [[ "$ha_ver" =~ ^[0-9]{4}\.[0-9]+\.[0-9]+$ ]] || { echo "Prerelease detected (${ha_ver}), skipping"; exit 0; }

          tmp_file=$(mktemp)
          jq --arg v "$ha_ver" '.homeassistant = $v' hacs.json > "$tmp_file"
          mv "$tmp_file" hacs.json

      - name: Commit updated hacs.json
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: sync hacs homeassistant version"
          file_pattern: hacs.json
