name: Move dev-snapshot tag

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all tags

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Move dev-snapshot tag to latest commit
        run: |
          git tag -d dev-snapshot || true
          git push origin :refs/tags/dev-snapshot || true
          git tag dev-snapshot
          git push origin dev-snapshot